language: ruby
rvm:
  - 2.2.3
services:
  - docker

# before_install:
#   - bundle exec rake test

install:
  - travis_retry docker build -t $DOCKER_IMAGE_NAME .

script:
  - docker run -d -p 4567:4567 $DOCKER_IMAGE_NAME

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.5.2
    - DOCKER_IMAGE_NAME=criticalmaps-api
