language: python

services:
  - docker

install:
  - travis_retry docker build -t $DOCKER_IMAGE_NAME .

script:
  - docker-compose up -d
  - docker ps | grep -q $DOCKER_IMAGE_NAME

env:
  global:
    - DOCKER_IMAGE_NAME=criticalmaps-api
