version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      DEBUG: "*"
      POSTGRES_USER: bla
      POSTGRES_PASSWORD: bla
      POSTGRES_PORT: 5432
      POSTGRES_DB: criticalmaps
    links:
      - postgres
    restart: always

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: bla
      POSTGRES_PASSWORD: bla
      POSTGRES_DB: criticalmaps
    expose:
        - "5432"
    restart: always
