web:
  build: .
  ports:
    - "3000:3000"
  environment:
    NODE_ENV: development
      #production
  links:
    - db
  restart: always
  environment:
    - POSTGRES_USER: bla
    - POSTGRES_PASSWORD: bla
    - POSTGRES_DB: criticalmaps

db:
  image: postgres
  environment:
    POSTGRES_USER: bla
    POSTGRES_PASSWORD: bla
    POSTGRES_DB: criticalmaps
  ports:
      - "5432:5432"
