version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      # web server
      - "3000:3000"
      # node-inspector
      - "5858:5858"
      - "8080:8080"
    expose:
      - "3000"
    environment:
      NODE_ENV: development
      DEBUG: "*"
      POSTGRES_USER: bla
      POSTGRES_PASSWORD: bla
      POSTGRES_PORT: 5432
      POSTGRES_DB: criticalmaps
    links:
      - postgres
    restart: always
    volumes:
      - .:/usr/src/app
    entrypoint: npm run nodemonstart

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: bla
      POSTGRES_PASSWORD: bla
      POSTGRES_DB: criticalmaps
    ports:
        - "5432:5432"

  pgweb:
    image: microbox/pgweb
    links:
      - postgres
    ports:
      - "8081:8080"
    environment:
      URL: "postgres://bla:bla@postgres:5432/criticalmaps?sslmode=disable"
    links:
      - postgres

  # phppgadmin:
  #   image: jacksoncage/phppgadmin
  #   depends_on:
  #     - postgres
  #   links:
  #     - postgres
  #   ports:
  #     - "8082:80"
  #   environment:
  #     APACHE_SERVERNAME: localhost
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #     POSTGRES_DEFAULTDB: criticalmaps
  #   links:
  #     - postgres
